name: This workflow will trigger repository dispatch

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "repository-dispatch-runner"
  repository-dispatch-runner:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v2
          with:
            token: ${{ secrets.ACCESS_TOKEN }}
            repository: soumalya5/Test-Automation
            event-type: on-push
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
